version: '3'

services:
  ispcontool:
    image: ispctl:latest
    restart: always
    environment:
      - TIME_INTERVAL=4
      - TIME_MODE=H
      - TIME_TOLERANCE=5
      - MAIN_ROUTINE_SLEEP=60
      - SUB_ROUTINE_SLEEP=120
      - SUB_RATE=1
    volumes:
      - /var/lib/docker/volumes/ispcontool/logs:/ispcontool/logs
      - /var/lib/docker/volumes/ispcontool/csv:/ispcontool/exports/csv
